[sftp.narnia]
host = "narnia.local"
user = "paradise"
port = 22
key_file = "~/.ssh/id_ed25519_no_passphrase"

[sftp.bignarnia]
host = "bignarnia.local"
user = "mimame"
port = 22
key_file = "~/.ssh/id_ed25519_no_passphrase"

[sftp.mininarnia]
host = "mininarnia.local"
user = "mimame"
port = 22
key_file = "~/.ssh/id_ed25519_no_passphrase"
