gui:
  # Lazygit Configuration - Dracula Theme
  # https://github.com/dracula/lazygit
  useHunkModeInStagingView: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#bd93f9'
      - bold
    inactiveBorderColor:
      - '#6272a4'
    optionsTextColor:
      - '#8be9fd'
    selectedLineBgColor:
      - '#44475a'
    cherryPickedCommitBgColor:
      - '#44475a'
    cherryPickedCommitFgColor:
      - '#50fa7b'
    unstagedChangesColor:
      - '#ff5555'
    defaultFgColor:
      - '#f8f8f2'
    searchingActiveBorderColor:
      - '#f1fa8c'
  authorColors:
    '*': '#bd93f9'
