[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#1e1e2e"
idle_fg = "#ffffff"
separator_bg = "#1e1e2e"
critical_bg = "#1e1e2e"
good_bg = "#1e1e2e"
info_bg = "#1e1e2e"
warning_bg = "#1e1e2e"

[icons]
icons = "material-nf"

[[block]]
block = "temperature"
interval = 2
format = " $icon $average avg, $max max "
chip = "*-isa-*"

[[block]]
block = "cpu"
interval = 2
format = " $icon $frequency $utilization $boost "
[[block.click]]
button = "left"
cmd = "wezterm -e btop"

[[block]]
block = "load"
format = " $icon $1m $5m $15m "
interval = 1

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
interval = 5
[[block.click]]
button = "left"
cmd = "cmst"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
format = " $icon / $available GB"
alert = 10
warning = 20
[[block.click]]
button = "left"
cmd = "wezterm -e gdu"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "time"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d %H:%M:%S') "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "pomodoro"
notify_cmd = "notifysend"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage {$time |} "

[[block]]
block = "backlight"
step_width = 1
minimum = 1

[[block]]
block = "sound"
step_width = 1
headphones_indicator = true
show_volume_when_muted = true
max_vol = 100
[[block.click]]
button = "left"
cmd = "pavucontrol"
