#!/bin/sh

# MIT License

# Copyright (c) 2018 Miguel Madrid Mencía

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Requirements:
  # acpi, pulseaudio, pamixer, dunst

# Description:
  # Interactive session menu close,

# Usage:
  # ./i3exit action
  # action: close, hibernate, lock, logout, suspend, reboot, restore, shutdown
NOTIFICATION=""
VOLUME="$(pamixer --sink "$(pactl list sinks short | grep -F RUNNING | cut -f1)" --get-volume)%"
DUNSTIFY_ID_FILE="/tmp/.dunstify_id"


case "$1" in
    no_battery)
        NOTIFICATION="Battery $(acpi -b | cut -d',' -f2)"
        ;;
    light)
        NOTIFICATION=" $(light -G | cut -d'.' -f1)%"
        ;;
    low_sound)
        NOTIFICATION=" $VOLUME"
        ;;
    high_sound)
        NOTIFICATION=" $VOLUME"
        ;;
    play-mute_sound)
        if [ "$(pamixer --sink "$(pactl list sinks short | grep -F RUNNING | cut -f1)" --get-mute)" = "true" ]; then
          NOTIFICATION=""
        else
          NOTIFICATION=" $VOLUME"
        fi
        ;;
    play-stop_song)
      if [ "$(playerctl status | grep -F Playing)" = "Playing" ]; then
          NOTIFICATION=""
        else
          NOTIFICATION=""
        fi
        ;;
    next_song)
        NOTIFICATION=""
        ;;
    previous_song)
        NOTIFICATION=""
        ;;
    i3horizontal_tiling)
        NOTIFICATION=" tiling"
        ;;
    i3vertical_tiling)
        NOTIFICATION=" tiling"
      ;;
    i3session_save)
        NOTIFICATION=" i3 session saved"
      ;;
    i3session_restore)
        NOTIFICATION=" i3 session restored"
      ;;
    screenshot)
        NOTIFICATION=" Screenshot saved to ~/Pictures"
      ;;
    *)
        dunstify --urgency=critical "Usage: $0 [i3session_save|i3session_restore|low_sound|high_sound|mute_sound|play-stop_song|next_song|previous_song]"
        exit 2
esac

DUNSTIFY_ID=$(cat "$DUNSTIFY_ID_FILE")
[ -e $DUNSTIFY_ID_FILE  ] && rm -f $DUNSTIFY_ID_FILE


if [ "$DUNSTIFY_ID" -gt "0" ]; then
  dunstify --replace "$DUNSTIFY_ID" --printid "$NOTIFICATION" > "$DUNSTIFY_ID_FILE"
else
  dunstify --printid "$NOTIFICATION" > "$DUNSTIFY_ID_FILE"
fi

exit 0
