#!/usr/bin/env bash
# https://www.reddit.com/r/i3wm/comments/a6xv7e/easy_workspace_renaming_with_no_external_scripts/
# https://github.com/infokiller/i3-workspace-groups/blob/master/scripts/i3-rename-workspace
new_workspace_name=$(rofi -dmenu -p 'New workspace name' -width 30 -location 0)
current_workspace_index=$(i3-msg -t get_workspaces | jq '.[] | select(.visible==true)' | jq '.num')

i3-msg "rename workspace to \"${current_workspace_index}: ${new_workspace_name}\""

i3-msg "append_layout ~/.config/i3/scripts/workspace.json"

alacritty &
firefox-developer-edition --new-window &
# wait at least 1 second to be sure the new tmux session was created
sleep 1
current_tmux_name=$(tmux list-sessions -F '#{session_name}' | sort --n | tail -n1)
tmux rename-session -t "$current_tmux_name" "$new_workspace_name"
