#!/usr/bin/env bash

# MIT License

# Copyright (c) 2018 Miguel Madrid Mencía

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Requirements:
# i3-wm, systemd, ./dunstify_notification, ./blurlock, ./i3session

# Description:
# Interactive session menu close,

# Usage:
# ./i3exit action
# action: close, hibernate, lock, logout, suspend, reboot, shutdown

BASE_DIR="$(dirname "$0")"

case "$1" in
close)
  wmctrl -l | cut -d' ' -f1 | xargs wmctrl -i -c
  ;;
hibernate)
  systemctl hibernate
  ;;
lock)
  "$BASE_DIR"/blurlock
  ;;
logout)
  i3-msg exit
  ;;
suspend)
  systemctl suspend
  ;;
reboot)
  wmctrl -l | cut -d' ' -f1 | xargs wmctrl -i -c && sleep 1
  systemctl reboot
  ;;
shutdown)
  wmctrl -l | cut -d' ' -f1 | xargs wmctrl -i -c && sleep 1
  systemctl poweroff
  ;;
*)
  echo "Usage: $0 [close|hibernate|lock|logout|reboot|suspend|shutdown]" 1>&2
  exit 1
  ;;
esac

exit 0
