#!/bin/bash

# https://github.com/yedhink
# Feel free to share with your friends

# install wmctrl. Its a prerequisite to make this script work.

# Launch it in your i3 config file
# exec --no-startup-id ~/.config/i3/init_workspace
#
# obviously, make it executable : # chmod +x init_workspace
# HAVE FUN !

# Changes done by Miguel Madrid Mencía
# - Remove explicit bin path to run the programs
# - Count opened windows by WM_CLASS to avoid count several multiple windows launched by Firefox
# - Wait in period of 1 second until the program is shown in the workspace

# App you want to start :
apps=(
  "firefox-developer-edition"
  "spotify"
  "google-chrome-stable"
  "thunderbird"
  "alacritty"
)

# Which workspace to assign your wanted App :
workspaces=(
  "2:  "
  "5:  "
  "2:  "
  "3:  "
  "1:  "
)

# counter of opened windows
owNB=0

for iwin in ${!apps[*]}; do
  # wait before start other programs
  while [ "$owNB" -lt "$iwin" ]; do
    # Count actual opened windows by WM_CLASS
    owNB=$(wmctrl -l -x | cut -d' ' -f4 | cut -d'.' -f2 | sort -u | wc -l)
    sleep 1
  done

  i3-msg workspace "${workspaces[$iwin]}" # move in wanted workspace
  "${apps[$iwin]}" &                      # start the wanted app
done
