[theme]
name = "plain"
[theme.overrides]
idle_bg = "#1e1e2e"
idle_fg = "#ffffff"
separator_bg = "#1e1e2e"
critical_bg = "#1e1e2e"
good_bg = "#1e1e2e"
idle_bg = "#1e1e2e"
info_bg = "#1e1e2e"
separator_bg = "#1e1e2e"
warning_bg = "#1e1e2e"

[icons]
name = "material-nf"

[[block]]
block = "temperature"
collapsed = false
interval = 2
format = "{average}"
chip = "*-isa-*"

[[block]]
block = "cpu"
on_click = "kitty -e btop"
interval = 2
critical = 90
warning = 60
info = 30
format = "{frequency} {utilization} {boost}"

[[block]]
block = "load"
format = "{1m} {5m} {15m}"
interval = 1

[[block]]
block = "net"
on_click = "kitty -e nmtui"
device = "eno1"
format = "{speed_up} {speed_down}"
interval = 5
hide_inactive = true

[[block]]
block = "net"
on_click = "kitty -e nmtui"
device = "enp4s0"
format = "{speed_up} {speed_down}"
interval = 5
hide_inactive = true

[[block]]
block = "net"
device = "wlp5s0"
format = "{ssid} {signal_strength} {speed_down;K*b} {speed_up;K*b}"
interval = 5
hide_inactive = true

[[block]]
block = "disk_space"
on_click = "kitty -e gdu"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
format = "{icon} / {available} GB"
alert = 10
warning = 20
alert_absolute = false

[[block]]
block = "memory"
format_mem = "{mem_free}"
format_swap = "{swap_free}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "time"
format = "%a %d %H:%M:%S"
interval = 1

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
notifier = "notifysend"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
hide_missing = true

[[block]]
block = "backlight"
step_width = 1

[[block]]
block = "sound"
step_width = 1
on_click = "pavucontrol"
headphones_indicator = true
show_volume_when_muted = true
