core:
  trash:
    strategy: auto
    home_fallback: true
    gomi_dir: ~/.gomi
  restore:
    confirm: true
    verbose: true
  permanent_delete:
    enable: false
  trash_dir: ""
ui:
  density: spacious
  style:
    list_view:
      indent_on_select: true
      cursor: "#BD93F9"
      selected: "#50FA7B"
    detail_view:
      border: "#F8F8F2"
      info_pane:
        deleted_from:
          fg: "#F8F8F2"
          bg: "#282A36"
        deleted_at:
          fg: "#F8F8F2"
          bg: "#282A36"
      preview_pane:
        border: "#44475A"
        size:
          fg: "#F8F8F2"
          bg: "#44475A"
        scroll:
          fg: "#F8F8F2"
          bg: "#44475A"
    deletion_dialog: "#FF5555"
  exit_message: ""
  preview:
    syntax_highlight: true
    colorscheme: dracula
    # directory_command: ls -GF -1 -A --color=always
    directory_command: eza --sort .name --color=always --long --links --group --git --icons --classify --extended --all --hyperlink
  paginator_type: dots
history:
  include:
    within_days: 365
  exclude:
    files:
      - .DS_Store
    patterns: []
    globs: []
    size:
      min: 0KB
      max: 10GB
logging:
  enabled: true
  level: debug
  rotation:
    max_size: 10MB
    max_files: 3
