---
- name: Update cache
  pacman:
    update_cache: true
  become: yes

- name: Install pacman packages
  pacman:
    name: "{{ item }}"
    state: present
  become: yes
  ignore_errors: yes
  with_items:
    - acpi
    - acpid
    - alacritty
    - arandr
    - aria2
    - asciidoc
    - aspell-en
    - at
    - atop
    - auto-cpufreq # if laptop
    - autoconf
    - automake
    - avfs
    - axel
    - baobab
    - barrier
    - bash-bats
    - bat
    - bind
    - bison
    - blueman
    - bluez-tools
    - bluez-utils
    - breeze-icons
    - broot
    - btop
    - bzip2
    - calibre
    - cheese
    - chrony # enable chronyd systemd service and be sure ntpd is disable
    - clang
    - cloc
    - cmake
    - cmatrix
    - cmus
    - coreutils
    - crystal
    - ctop
    - curlie
    - difftastic
    - direnv
    - diskus
    - docker
    - docker-compose
    - dog
    - dos2unix
    - downgrade
    - dpkg
    - dstat
    - dua-cli
    - duf
    - dunst
    - dust
    - e2fsprogs
    - entr
    - eog
    - ethtool
    - evince
    - exa
    - exfat-utils
    - f2fs-tools
    - fakeroot
    - fd
    - feh
    - ffmpeg
    - filezilla
    - firefox
    - fish
    - flameshot
    - fuse-zip
    - fzf
    - gawk
    - gcc
    - gcc-fortran
    - gcc-libs
    - gdu
    - geoclue
    - gephi
    - gettext
    - gimp
    - gitg
    - github-cli
    - gitui
    - glances
    - glow
    - go
    - gopls
    - gparted
    - graphviz
    - grc
    - grex
    - gthumb
    - gufw
    - gvfs-afc
    - gvfs-google
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-smb
    - gzip
    - harfbuzz-icu
    - hexyl
    - htop
    - httpie
    - httrack
    - hugo
    - hyperfine
    - hyphen-en
    - hyphen-es
    - hyphen-fr
    - i3-wm
    - i3status-rust
    - igraph
    - inetutils
    - inkscape
    - ipython
    - isousb
    - jdk-openjdk
    - jq
    - jre11-openjdk
    - jre11-openjdk-headless
    - just
    - keepassxc
    - klavaro
    - lazygit
    - less
    - libinput-gestures
    - libreoffice-fresh
    - light # laptop mode
    - llvm
    - lnav
    - logrotate
    - lsd
    - lsof
    - lsscsi
    - lua-language-server
    - lxappearance
    - macchanger
    - make
    - man-db
    - man-pages
    - mdcat
    - meld
    - micro
    - mlocate
    - mosh
    - mpv
    - mtr
    - neovim
    - neovim-qt
    - netctl
    - network-manager-applet
    - networkmanager-openconnect
    - networkmanager-openvpn
    - networkmanager-pptp
    - networkmanager-vpnc
    - newsboat
    - nfs-utils
    - nim
    - nimble
    - npm
    - ntfs-3g
    - numlockx # disabled by default
    - nuspell
    - opencl-headers
    - openfortivpn
    - openshot
    - opera
    - p7zip
    - pamac-gtk
    - pamixer
    - parallel
    - patch
    - pavucontrol
    - pbzip2
    - pcmanfm-gtk
    - pcmanfm-gtk3
    - perl-anyevent-i3
    - perl-file-mimeinfo
    - pigz
    - pipewire
    - pipewire-alsa
    - pipewire-jack
    - pipewire-pulse
    - pixz
    - pkgconf
    - plantuml
    - playerctl
    - podman
    - polkit-gnome
    - procs
    - progress
    - pueue
    - putty
    - pv
    - pwgen
    - python-pip
    - python-pynvim
    - python-xlrd
    - r
    - ranger
    - rclone
    - redshift
    - ripgrep
    - rofi
    - rsync
    - ruby
    - rustup
    - screen
    - screenfetch
    - sd
    - seahorse
    - shards
    - shfmt
    - singularity-container
    - smartmontools
    - speedtest-cli
    - sshfs
    - sshpass
    - starship
    - stow
    - strace
    - stress
    - sudo
    - sysstat
    - tealdeer
    - tela-icon-theme
    - telegram-desktop
    - terminator
    - tesseract-data-eng
    - texinfo
    - texlab
    - texlive-bibtexextra
    - texlive-core
    - texlive-latexextra
    - texlive-science
    - thunderbird-i18n-en-us
    - tig
    - time
    - tk
    - tmuxp
    - tokei
    - topgrade
    - translate-shell
    - tree
    - udiskie
    - udisks2
    - unrar
    - urlscan
    - vagrant
    - vifm
    - virtualbox
    - vivid
    - vlc
    - wget
    - which
    - wireplumber
    - wireshark-qt
    - wmctrl
    - wmutils
    - words
    - xarchiver
    - xautolock
    - xcape
    - xclip
    - xdg-utils
    - xdotool
    - xh
    - xorg-xbacklight # if laptop
    - xorg-xev
    - xsel
    - yamllint
    - yarn
    - yay
    - zathura-pdf-mupdf
    - zig
    - zsh
    - zstd

- name: Delete all downloaded packages and temporal cache
  pacman:
    update_cache: true
  become: yes

- name: Disable useless GNOME file tracker dependency and service
  command: systemctl --user mask tracker-extract-3.service tracker-miner-fs-3.service tracker-miner-rss-3.service tracker-writeback-3.service tracker-xdg-portal-3.service tracker-miner-fs-control-3.service

- name: Enable pueue service
  command: systemctl --user start pueued.service && systemctl --user enable pueued.service
